"""Add is_synthetic flag

Revision ID: 5bc2072bb07e
Revises: 893809d930f4
Create Date: 2026-02-16 10:48:23.355840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc2072bb07e'
down_revision: Union[str, Sequence[str], None] = '893809d930f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_reports', sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect_reports', 'is_synthetic')
    # ### end Alembic commands ###
