"""Add description field to DefectReport

Revision ID: c51c816c4df1
Revises: dbe891926180
Create Date: 2026-02-16 08:45:45.951135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51c816c4df1'
down_revision: Union[str, Sequence[str], None] = 'dbe891926180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_reports', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect_reports', 'description')
    # ### end Alembic commands ###
