"""Add latitude and longitude to DefectReport

Revision ID: d545532c2560
Revises: c51c816c4df1
Create Date: 2026-02-16 08:52:46.438725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd545532c2560'
down_revision: Union[str, Sequence[str], None] = 'c51c816c4df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('defect_reports', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect_reports', 'longitude')
    op.drop_column('defect_reports', 'latitude')
    # ### end Alembic commands ###
