"""Initial migration

Revision ID: dbe891926180
Revises: 
Create Date: 2026-02-16 08:19:14.126329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe891926180'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('station', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_reports_category'), 'defect_reports', ['category'], unique=False)
    op.create_index(op.f('ix_defect_reports_id'), 'defect_reports', ['id'], unique=False)
    op.create_index(op.f('ix_defect_reports_station'), 'defect_reports', ['station'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defect_reports_station'), table_name='defect_reports')
    op.drop_index(op.f('ix_defect_reports_id'), table_name='defect_reports')
    op.drop_index(op.f('ix_defect_reports_category'), table_name='defect_reports')
    op.drop_table('defect_reports')
    # ### end Alembic commands ###
